spring.application.name=backend
spring.config.import=optional:application-secrets.properties

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/yforge_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${spring.datasource.password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${jwt.secret}
jwt.expiration-ms=86400000

server.port=${PORT:8080}